trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: benchmarkJobType
  type: string
  values: [ dry, short, medium, long ]
  default: dry

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - powershell: docker --version
    displayName: "Docker Information"

  - powershell: |
      docker pull mcr.microsoft.com/presidio-analyzer
      docker pull mcr.microsoft.com/presidio-anonymizer
      docker run -d -p 5001:3000 mcr.microsoft.com/presidio-analyzer:latest
      docker run -d -p 5002:3000 mcr.microsoft.com/presidio-anonymizer:latest
      docker ps
    displayName: "Setup Presidio"

  - powershell: |
      docker build -t fhircli-benchmark -f benchmark/Dockerfile .
    displayName: "Build Benchmark container"
  
  - powershell: |
      docker run --mount src=$(Build.StagingDirectory),target=/benchmark/src/Microsoft.Health.Fhir.Anonymizer.Stu3.Benchmarks/BenchmarkDotNet.Artifacts,type=bind --privileged -it fhircli-benchmark --job ${{ parameters.benchmarkJobType }} --filter *FullFlow*
    displayName: "Run Benchmark container"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)'
      ArtifactName: 'benchmark-artifacts'
      publishLocation: 'Container'