trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: benchmarkJobType
  type: string
  values: [ dry, short, medium, long ]
  default: dry

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - powershell: docker --version
    displayName: "Docker Information"

  - powershell: |
      docker pull mcr.microsoft.com/presidio-analyzer
      docker pull mcr.microsoft.com/presidio-anonymizer
      docker run -d -p 5001:3000 mcr.microsoft.com/presidio-analyzer:latest
      docker run -d -p 5002:3000 mcr.microsoft.com/presidio-anonymizer:latest
      docker ps
    displayName: "Setup Presidio"

  - task: PowerShell@2
    displayName: "Build Benchmark container"
    inputs:
      targetType: 'inline'
      script: 'docker build -t fhircli-benchmark -f benchmark/Dockerfile .'
      pwsh: true
  
  - task: PowerShell@2
    displayName: "Run Benchmark container"
    inputs:
      targetType: 'inline'
      script: 'docker run --mount src=$(Build.StagingDirectory),target=/benchmark/src/Microsoft.Health.Fhir.Anonymizer.Stu3.Benchmarks/BenchmarkDotNet.Artifacts,type=bind --privileged  fhircli-benchmark --job ${{ parameters.benchmarkJobType }} --filter *FullFlow*'
      pwsh: true  

  - task: PublishBuildArtifacts@1
    displayName: "Collect Results"
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)'
      ArtifactName: 'benchmark-artifacts'
      publishLocation: 'Container'