trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: benchmarkJobType
  type: string
  values: [ dry, short, medium, long ]
  default: dry

variables:
- name: JOB_TYPE
  value: '${{ parameters.benchmarkJobType }}'

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - powershell: docker --version
    displayName: "Docker Information"

  - powershell: |
      docker-compose build
    displayName: "Docker-compose build"
  
  - powershell: |
      docker-compose up
    displayName: "Docker-compose up" 

  - task: PublishBuildArtifacts@1
    displayName: "Collect Results"
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)'
      ArtifactName: 'benchmark-artifacts'
      publishLocation: 'Container'

