trigger:
  none

variables:
  benchmarkRoot: c:/fhircli/benchmarks
  benchmarkRunnerAccountName: benchmark_runner
  benchmarkMachines: fhir-cli-benchmarks
  ServiceConnectionId: 81264a6f-8ced-45f8-8b1f-20830309bd66

pool:
  vmImage: windows-latest

steps:
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'filessource'
    MachineNames: '$(benchmarkMachines)'
    AdminUserName: '$(benchmarkRunnerAccountName)'
    AdminPassword: '$(benchmark.password)'
    TargetPath: '$(benchmarkRoot)\src'
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'filessource'
    MachineNames: '$(benchmarkMachines)'
    AdminUserName: '$(benchmarkRunnerAccountName)'
    AdminPassword: '$(benchmark.password)'
    TargetPath: '$(benchmarkRoot)\src'
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '$(benchmarkMachines)'
    UserName: '$(benchmarkRunnerAccountName)'
    UserPassword: '$(benchmark.password)'
    ScriptType: 'FilePath'
    ScriptPath: '$(benchmarkRoot)\src\run_benchmarks.ps1'
    ScriptArguments: 'args'