trigger:
  none

variables:
  - group: Benchmark-pipeline-variable

parameters:
- name: BenchmarkJobType
  type: string
  values: [ short,medium,long ]
  default: short

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    arguments: '-c Release -- --job ${{ parameters.BenchmarkJobType }} --memory --runtimes netcoreapp3.1 --filter *FullFlow*'
    workingDirectory: '$(Build.SourcesDirectory)\src\Microsoft.Health.Fhir.Anonymizer.Stu3.Benchmarks'

