trigger:
  none

variables:
  - group: Benchmark-pipeline-variable

parameters:
- name: BenchmarkJobType
  type: string
  values: [ short,medium,long ]
  default: short

pool:
  vmImage: windows-latest

steps:
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.Repository.LocalPath)\samples'
    MachineNames: '$(Benchmark.VMResourceGroup)'
    AdminUserName: '$(Benchmark.VMAccountName)'
    AdminPassword: '$(Benchmark.VMPassword)'
    TargetPath: '$(Benchmark.RootPath)\samples'
    CleanTargetBeforeCopy: true
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.Repository.LocalPath)\src'
    MachineNames: '$(Benchmark.VMResourceGroup)'
    AdminUserName: '$(benchmarkRunnerAccountName)'
    AdminPassword: '$(Benchmark.VMPassword)'
    TargetPath: '$(Benchmark.RootPath)\src'
    CleanTargetBeforeCopy: true
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '$(Benchmark.VMResourceGroup)'
    UserName: '$(Benchmark.VMAccountName)'
    UserPassword: '$(Benchmark.VMPassword)'
    ScriptType: 'FilePath'
    ScriptPath: '$(Benchmark.RootPath)\src\run_benchmarks.ps1'
    ScriptArguments:  ${{ parameters.BenchmarkJobType }}